export const classForBadges = {
  html: "bg-html border border-html  hover:text-html",
  css: "bg-css border border-css  hover:text-css",
  javascript: "bg-js border border-js  hover:text-white dark:hover:text-js",
  react: "bg-react border border-react  hover:text-react",
  tailwind: "bg-tailwind border border-tailwind  hover:text-tailwind",
  nodejs: "bg-nodejs border border-nodejs  hover:text-nodejs",
  express: "bg-express border border-express  hover:text-express",
  mysql: "bg-mysql border border-mysql  hover:text-mysql",
  firebase: "bg-firebase border border-firebase hover:text-firebase",
  astro: "bg-astro border border-astro hover:text-astro",
  mongodb: "bg-mongodb border border-mongodb hover:text-mongodb",
  php: "bg-php border border-php hover:text-php",
  laravel: "bg-laravel border border-laravel hover:text-laravel",
};
